# fly.toml app configuration file for REmind UI
app = "remind-ui"
primary_region = "iad"

[build]

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/"

[processes]
  app = "npx"

[deploy]
  release_command = "echo 'Deploying REmind UI'"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 128
